<?php

use App\Http\Controllers\Api\AccountBlockController;
use App\Http\Controllers\Api\AdminAccountController;
use App\Http\Controllers\Api\AdminAuditLogController;
use App\Http\Controllers\Api\AdminBookingController;
use App\Http\Controllers\Api\AdminContactInquiryController;
use App\Http\Controllers\Api\AdminDashboardController;
use App\Http\Controllers\Api\AdminIdentityVerificationController;
use App\Http\Controllers\Api\AdminLegalDocumentController;
use App\Http\Controllers\Api\AdminPayoutRequestController;
use App\Http\Controllers\Api\AdminPlatformFeeSettingController;
use App\Http\Controllers\Api\AdminProfilePhotoController;
use App\Http\Controllers\Api\AdminRefundRequestController;
use App\Http\Controllers\Api\AdminReportController;
use App\Http\Controllers\Api\AdminStripeDisputeController;
use App\Http\Controllers\Api\AdminTherapistProfileController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\BookingCancellationController;
use App\Http\Controllers\Api\BookingController;
use App\Http\Controllers\Api\BookingMessageController;
use App\Http\Controllers\Api\BookingQuoteController;
use App\Http\Controllers\Api\BookingStatusController;
use App\Http\Controllers\Api\ContactController;
use App\Http\Controllers\Api\HelpFaqController;
use App\Http\Controllers\Api\IdentityVerificationController;
use App\Http\Controllers\Api\LegalDocumentController;
use App\Http\Controllers\Api\MeProfileController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\PaymentIntentController;
use App\Http\Controllers\Api\PaymentSyncController;
use App\Http\Controllers\Api\ProfilePhotoController;
use App\Http\Controllers\Api\PushSubscriptionController;
use App\Http\Controllers\Api\RefundRequestController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\ReviewController;
use App\Http\Controllers\Api\ServiceAddressController;
use App\Http\Controllers\Api\ServiceMetaController;
use App\Http\Controllers\Api\StripeConnectController;
use App\Http\Controllers\Api\StripeWebhookController;
use App\Http\Controllers\Api\TempFileController;
use App\Http\Controllers\Api\TherapistAvailabilitySlotController;
use App\Http\Controllers\Api\TherapistDiscoveryController;
use App\Http\Controllers\Api\TherapistLedgerController;
use App\Http\Controllers\Api\TherapistMenuController;
use App\Http\Controllers\Api\TherapistPayoutRequestController;
use App\Http\Controllers\Api\TherapistProfileController;
use App\Http\Controllers\Api\TherapistScheduledBookingSettingController;
use App\Http\Controllers\Api\UserProfileController;
use Illuminate\Support\Facades\Route;

Route::post('/webhooks/stripe', StripeWebhookController::class);

Route::prefix('auth')->group(function (): void {
    Route::post('/register', [AuthController::class, 'register']);
    Route::post('/login', [AuthController::class, 'login']);
});

Route::get('/legal-documents', [LegalDocumentController::class, 'index']);
Route::get('/legal-documents/{type}', [LegalDocumentController::class, 'showLatest']);
Route::get('/service-meta', [ServiceMetaController::class, 'show']);
Route::get('/help/faqs', [HelpFaqController::class, 'index']);
Route::post('/contact', [ContactController::class, 'store']);

Route::middleware('auth:sanctum')->group(function (): void {
    Route::get('/me', [AuthController::class, 'me']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::post('/legal-documents/{legalDocument:public_id}/accept', [LegalDocumentController::class, 'accept']);
    Route::get('/me/profile', [MeProfileController::class, 'show']);
    Route::patch('/me/profile', [MeProfileController::class, 'update']);
    Route::post('/me/profile/photos', [ProfilePhotoController::class, 'store']);
    Route::delete('/me/profile/photos/{profilePhoto}', [ProfilePhotoController::class, 'destroy']);
    Route::get('/me/user-profile', [UserProfileController::class, 'show']);
    Route::put('/me/user-profile', [UserProfileController::class, 'upsert']);
    Route::patch('/me/user-profile/sensitive-disclosure', [UserProfileController::class, 'updateSensitiveDisclosure']);

    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'read']);
    Route::post('/push-subscriptions', [PushSubscriptionController::class, 'store']);
    Route::delete('/push-subscriptions/{pushSubscription}', [PushSubscriptionController::class, 'destroy']);
    Route::post('/accounts/{account:public_id}/block', [AccountBlockController::class, 'store']);
    Route::delete('/accounts/{account:public_id}/block', [AccountBlockController::class, 'destroy']);
    Route::post('/reports', [ReportController::class, 'store']);
    Route::get('/reports/{report:public_id}', [ReportController::class, 'show']);
    Route::get('/admin/refund-requests', [AdminRefundRequestController::class, 'index']);
    Route::post('/admin/refund-requests/{refund:public_id}/approve', [AdminRefundRequestController::class, 'approve']);
    Route::post('/admin/refund-requests/{refund:public_id}/reject', [AdminRefundRequestController::class, 'reject']);
    Route::get('/admin/payout-requests', [AdminPayoutRequestController::class, 'index']);
    Route::post('/admin/payout-requests/{payoutRequest:public_id}/hold', [AdminPayoutRequestController::class, 'hold']);
    Route::post('/admin/payout-requests/{payoutRequest:public_id}/release', [AdminPayoutRequestController::class, 'release']);
    Route::post('/admin/payout-requests/{payoutRequest:public_id}/process', [AdminPayoutRequestController::class, 'process']);
    Route::get('/admin/identity-verifications', [AdminIdentityVerificationController::class, 'index']);
    Route::post('/admin/identity-verifications/{identityVerification}/approve', [AdminIdentityVerificationController::class, 'approve']);
    Route::post('/admin/identity-verifications/{identityVerification}/reject', [AdminIdentityVerificationController::class, 'reject']);
    Route::get('/admin/therapist-profiles', [AdminTherapistProfileController::class, 'index']);
    Route::get('/admin/therapist-profiles/{therapistProfile:public_id}', [AdminTherapistProfileController::class, 'show']);
    Route::post('/admin/therapist-profiles/{therapistProfile:public_id}/approve', [AdminTherapistProfileController::class, 'approve']);
    Route::post('/admin/therapist-profiles/{therapistProfile:public_id}/reject', [AdminTherapistProfileController::class, 'reject']);
    Route::post('/admin/therapist-profiles/{therapistProfile:public_id}/suspend', [AdminTherapistProfileController::class, 'suspend']);
    Route::post('/admin/therapist-profiles/{therapistProfile:public_id}/restore', [AdminTherapistProfileController::class, 'restore']);
    Route::get('/admin/profile-photos', [AdminProfilePhotoController::class, 'index']);
    Route::post('/admin/profile-photos/{profilePhoto}/approve', [AdminProfilePhotoController::class, 'approve']);
    Route::post('/admin/profile-photos/{profilePhoto}/reject', [AdminProfilePhotoController::class, 'reject']);
    Route::get('/admin/reports', [AdminReportController::class, 'index']);
    Route::get('/admin/reports/{report:public_id}', [AdminReportController::class, 'show']);
    Route::post('/admin/reports/{report:public_id}/actions', [AdminReportController::class, 'action']);
    Route::post('/admin/reports/{report:public_id}/resolve', [AdminReportController::class, 'resolve']);
    Route::get('/admin/bookings', [AdminBookingController::class, 'index']);
    Route::get('/admin/bookings/{booking:public_id}', [AdminBookingController::class, 'show']);
    Route::get('/admin/bookings/{booking:public_id}/messages', [AdminBookingController::class, 'messages']);
    Route::post('/admin/bookings/{booking:public_id}/messages/{message}/notes', [AdminBookingController::class, 'note']);
    Route::post('/admin/bookings/{booking:public_id}/messages/{message}/moderation', [AdminBookingController::class, 'moderate']);
    Route::post('/admin/bookings/{booking:public_id}/messages/{message}/reports', [AdminBookingController::class, 'createReport']);
    Route::post('/admin/bookings/{booking:public_id}/messages/{message}/suspend-sender', [AdminBookingController::class, 'suspendSender']);
    Route::get('/admin/stripe-disputes', [AdminStripeDisputeController::class, 'index']);
    Route::get('/admin/dashboard', [AdminDashboardController::class, 'index']);
    Route::get('/admin/accounts', [AdminAccountController::class, 'index']);
    Route::get('/admin/accounts/{account:public_id}', [AdminAccountController::class, 'show']);
    Route::post('/admin/accounts/{account:public_id}/suspend', [AdminAccountController::class, 'suspend']);
    Route::post('/admin/accounts/{account:public_id}/restore', [AdminAccountController::class, 'restore']);
    Route::get('/admin/audit-logs', [AdminAuditLogController::class, 'index']);
    Route::get('/admin/platform-fee-settings', [AdminPlatformFeeSettingController::class, 'index']);
    Route::post('/admin/platform-fee-settings', [AdminPlatformFeeSettingController::class, 'store']);
    Route::get('/admin/legal-documents', [AdminLegalDocumentController::class, 'index']);
    Route::post('/admin/legal-documents', [AdminLegalDocumentController::class, 'store']);
    Route::patch('/admin/legal-documents/{legalDocument}', [AdminLegalDocumentController::class, 'update']);
    Route::get('/admin/contact-inquiries', [AdminContactInquiryController::class, 'index']);
    Route::get('/admin/contact-inquiries/{contactInquiry:public_id}', [AdminContactInquiryController::class, 'show']);
    Route::post('/admin/contact-inquiries/{contactInquiry:public_id}/notes', [AdminContactInquiryController::class, 'note']);
    Route::post('/admin/contact-inquiries/{contactInquiry:public_id}/resolve', [AdminContactInquiryController::class, 'resolve']);
    Route::get('/therapists', [TherapistDiscoveryController::class, 'index'])->middleware('throttle:therapist-search');
    Route::get('/therapists/{therapistProfile:public_id}', [TherapistDiscoveryController::class, 'show']);
    Route::get('/therapists/{therapistProfile:public_id}/reviews', [ReviewController::class, 'therapistReviews']);
    Route::get('/me/reviews', [ReviewController::class, 'me']);

    Route::post('/temp-files', [TempFileController::class, 'store']);
    Route::delete('/temp-files/{tempFile:file_id}', [TempFileController::class, 'destroy']);

    Route::get('/me/identity-verification', [IdentityVerificationController::class, 'latest']);
    Route::post('/me/identity-verification', [IdentityVerificationController::class, 'store']);

    Route::get('/me/service-addresses', [ServiceAddressController::class, 'index']);
    Route::post('/me/service-addresses', [ServiceAddressController::class, 'store']);
    Route::get('/me/service-addresses/{serviceAddress:public_id}', [ServiceAddressController::class, 'show']);
    Route::delete('/me/service-addresses/{serviceAddress:public_id}', [ServiceAddressController::class, 'destroy']);

    Route::get('/me/therapist-profile', [TherapistProfileController::class, 'show']);
    Route::put('/me/therapist-profile', [TherapistProfileController::class, 'upsert']);
    Route::post('/me/therapist-profile/submit-review', [TherapistProfileController::class, 'submitReview']);
    Route::get('/me/therapist-profile/review-status', [TherapistProfileController::class, 'reviewStatus']);
    Route::put('/me/therapist/location', [TherapistProfileController::class, 'updateLocation']);
    Route::get('/me/therapist/scheduled-booking-settings', [TherapistScheduledBookingSettingController::class, 'show']);
    Route::put('/me/therapist/scheduled-booking-settings', [TherapistScheduledBookingSettingController::class, 'upsert']);
    Route::get('/me/therapist/availability-slots', [TherapistAvailabilitySlotController::class, 'index']);
    Route::post('/me/therapist/availability-slots', [TherapistAvailabilitySlotController::class, 'store']);
    Route::patch('/me/therapist/availability-slots/{therapistAvailabilitySlot:public_id}', [TherapistAvailabilitySlotController::class, 'update']);
    Route::delete('/me/therapist/availability-slots/{therapistAvailabilitySlot:public_id}', [TherapistAvailabilitySlotController::class, 'destroy']);
    Route::get('/me/therapist/menus', [TherapistMenuController::class, 'index']);
    Route::post('/me/therapist/menus', [TherapistMenuController::class, 'store']);
    Route::patch('/me/therapist/menus/{therapistMenu:public_id}', [TherapistMenuController::class, 'update']);
    Route::delete('/me/therapist/menus/{therapistMenu:public_id}', [TherapistMenuController::class, 'destroy']);
    Route::get('/me/therapist/ledger', [TherapistLedgerController::class, 'index']);
    Route::get('/me/therapist/payout-requests', [TherapistPayoutRequestController::class, 'index']);
    Route::post('/me/therapist/payout-requests', [TherapistPayoutRequestController::class, 'store']);
    Route::get('/me/therapist/payout-requests/{payoutRequest:public_id}', [TherapistPayoutRequestController::class, 'show']);
    Route::get('/me/stripe-connect', [StripeConnectController::class, 'show']);
    Route::post('/me/stripe-connect/accounts', [StripeConnectController::class, 'createAccount']);
    Route::post('/me/stripe-connect/account-link', [StripeConnectController::class, 'createAccountLink']);
    Route::post('/me/stripe-connect/refresh', [StripeConnectController::class, 'refresh']);

    Route::post('/booking-quotes', [BookingQuoteController::class, 'store']);
    Route::get('/me/therapist/booking-requests', [BookingController::class, 'therapistRequests']);
    Route::get('/bookings', [BookingController::class, 'index']);
    Route::post('/bookings', [BookingController::class, 'store']);
    Route::get('/bookings/{booking:public_id}', [BookingController::class, 'show']);
    Route::post('/bookings/{booking:public_id}/payment-intents', [PaymentIntentController::class, 'store']);
    Route::post('/bookings/{booking:public_id}/payment-sync', [PaymentSyncController::class, 'store']);
    Route::post('/bookings/{booking:public_id}/cancel-preview', [BookingCancellationController::class, 'preview']);
    Route::post('/bookings/{booking:public_id}/cancel', [BookingCancellationController::class, 'store']);
    Route::get('/bookings/{booking:public_id}/refund-requests', [RefundRequestController::class, 'index']);
    Route::post('/bookings/{booking:public_id}/refund-requests', [RefundRequestController::class, 'store']);
    Route::get('/bookings/{booking:public_id}/messages', [BookingMessageController::class, 'index']);
    Route::post('/bookings/{booking:public_id}/messages', [BookingMessageController::class, 'store']);
    Route::post('/bookings/{booking:public_id}/messages/{message}/read', [BookingMessageController::class, 'read']);
    Route::post('/bookings/{booking:public_id}/reviews', [ReviewController::class, 'store']);
    Route::get('/refund-requests/{refund:public_id}', [RefundRequestController::class, 'show']);
    Route::post('/bookings/{booking:public_id}/accept', [BookingStatusController::class, 'accept']);
    Route::post('/bookings/{booking:public_id}/reject', [BookingStatusController::class, 'reject']);
    Route::post('/bookings/{booking:public_id}/moving', [BookingStatusController::class, 'moving']);
    Route::post('/bookings/{booking:public_id}/arrived', [BookingStatusController::class, 'arrived']);
    Route::post('/bookings/{booking:public_id}/start', [BookingStatusController::class, 'start']);
    Route::post('/bookings/{booking:public_id}/complete', [BookingStatusController::class, 'complete']);
    Route::post('/bookings/{booking:public_id}/user-complete-confirmation', [BookingStatusController::class, 'userCompleteConfirmation']);
});
